name: Deploy to cPanel
on:
  push:
    branches: [main] # or master, depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # or whatever version you're using

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: 📂 Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.CPANEL_SERVER }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          local-dir: ./build/ # or ./dist/ depending on your build output
          server-dir: /home/mediades/firme.mediadesignro.ro/public_html/
